### PR TITLE
had accessors.Rd file written

### PR DESCRIPTION
**Pull request by EricArcher**
and added EA to DESCRIPTION

### CODE REVIEW

**Comment by EricArcher** [comment]
modified exclude.all.gaps argument functionality in accessors

**Comment by thibautjombart** [comment]
OK, trying to merge conflicts, but unsure what is broken now - this bit or the last push from @KlausVigo ;)

**Comment by KlausVigo** [comment]
I will have a look at it. 
k

**Comment by thibautjombart** [comment]
I think it's sorted now! =D

**Comment by thibautjombart** [comment]
@EricArcher can you confirm the current master has what it should?

**Comment by EricArcher** [comment]
merged `gap.only` and `exclude.gap.only` arguments into latter and changed code to return sequences without all gaps (seemed more useful to me). All consistent now.

**Comment by thibautjombart** [comment]
Cool!

**Pull request closed without merging**
