### PR TITLE
Add extra arguments to further address #2

### PR DESCRIPTION
**Pull request by zkamvar**
This appears to pass check. 

`mlst = TRUE` will render the resulting genind object with the number of loci equal to the number of genes.

`gapIsNA = TRUE` will turn genes that are all gaps to NAs.

Both of these are off by default.

### CODE REVIEW

**Comment by thibautjombart** [comment]
Looks great!

**Comment by zkamvar** [comment]
Can this branch be merged?

**Comment by thibautjombart** [comment]
I am merging it but there are problems. Your branch is fine, but @KlausVigo pushed changes on the master branch which break the package.

**Comment by thibautjombart** [comment]
Can't easily re-merge into an older state without messing around. I'll push as is and disable stuff that's broken.

**Pull request merged**
